### ISSUE TITLE
status of this repo

### ISSUE THREAD

**Issue by nurey** [splitrb/split-api#2]
I am wondering about the status of this repository with respect to functionality.

Looking at the code, the `/finished` endpoint is calling a method (`finished`) that doesn't exist in Split::Helper module.

Changing `finished` to `ab_finished` seems to work.

I would like to use this gem to run experiments for users of an Ember app. The XHR request to get an alternative for an experiment (`/ab_test`) is working as expected, but the `POST /finished` request doesn't actually complete an experiment for a particular user. I'm guessing this is because split can't find a user at that point. It looks like I need to create a persistence adapter. I was thinking I would change `GET /ab_test` to return a uuid along with the alternative, Ember would store the uuid and pass that into the `POST /finished`. 

Thoughts?

**Comment by andrew** [comment]
This repo is hasn't been touched in ~2 years so I expect it's compatibility has drifted a bit with newer versions of split, I'd be happy to accept any PRs to fix it up.

**Comment by andrew** [comment]
@nurey I just did a quick fixup of the test suite and got it working with split > 2.0, published on rubygems as 0.0.2: https://rubygems.org/gems/split-api/versions/0.0.2
